package br.com.gymapp

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import br.com.gymapp.domain.model.*
import br.com.gymapp.feature.*
import br.com.gymapp.ui.theme.GymAppTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); enableEdgeToEdge(); setContent { GymAppTheme { GymApp() } } }
}

@Composable fun GymApp(vm: GymViewModel = viewModel()) { val state by vm.state.collectAsState(); Surface(Modifier.fillMaxSize()) { when (state.screen) { AppScreen.Login -> LoginScreen(state, vm::login); AppScreen.Home -> HomeScreen(state, vm::select); AppScreen.Details -> DetailsScreen(state, vm::startWorkout, vm::home); AppScreen.Session -> SessionScreen(state, vm); AppScreen.Summary -> SummaryScreen(state, vm::home) } } }

@Composable private fun LoginScreen(state: GymUiState, onLogin: (String, String) -> Unit) { var email by remember { mutableStateOf("") }; var password by remember { mutableStateOf("") }; Column(Modifier.fillMaxSize().padding(28.dp), verticalArrangement = Arrangement.Center) { Text("GYM/", fontSize = 42.sp, fontWeight = FontWeight.Black, color = MaterialTheme.colorScheme.primary); Text("Seu treino começa aqui.", style = MaterialTheme.typography.titleLarge); Spacer(Modifier.height(32.dp)); OutlinedTextField(email, { email = it }, Modifier.fillMaxWidth(), label = { Text("E-mail") }, singleLine = true); Spacer(Modifier.height(12.dp)); OutlinedTextField(password, { password = it }, Modifier.fillMaxWidth(), label = { Text("Senha") }, visualTransformation = PasswordVisualTransformation(), singleLine = true); state.error?.let { Text(it, color = MaterialTheme.colorScheme.error, modifier = Modifier.padding(top = 10.dp)) }; Spacer(Modifier.height(20.dp)); Button({ onLogin(email, password) }, Modifier.fillMaxWidth().height(54.dp), enabled = !state.loading, shape = RoundedCornerShape(16.dp)) { if (state.loading) CircularProgressIndicator(Modifier.size(22.dp), color = Color.White) else Text("ENTRAR", fontWeight = FontWeight.Bold) }; Text("Use o e-mail e a senha cadastrados no backend.", style = MaterialTheme.typography.bodySmall, modifier = Modifier.padding(top = 14.dp)) } }

@Composable private fun HomeScreen(state: GymUiState, select: (Workout) -> Unit) { LazyColumn(Modifier.fillMaxSize().padding(horizontal = 20.dp), contentPadding = PaddingValues(top = 56.dp, bottom = 24.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) { item { Text("Olá, ${state.user?.name ?: "atleta"}.", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold); Text("Pronto para treinar?", color = MaterialTheme.colorScheme.onSurfaceVariant) }; item { Text("TREINO DE HOJE", style = MaterialTheme.typography.labelLarge, color = MaterialTheme.colorScheme.primary, modifier = Modifier.padding(top = 18.dp)) }; items(state.workouts) { workout -> WorkoutCard(workout, select) } } }
@Composable private fun WorkoutCard(workout: Workout, select: (Workout) -> Unit) { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(24.dp), colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)) { Column(Modifier.padding(20.dp)) { Text(workout.name, style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold); Text(workout.description.orEmpty(), style = MaterialTheme.typography.bodyLarge); Text("${workout.exerciseCount} exercícios  •  ~${workout.estimatedMinutes} min", modifier = Modifier.padding(vertical = 18.dp), color = MaterialTheme.colorScheme.onSurfaceVariant); Button({ select(workout) }, Modifier.fillMaxWidth(), shape = RoundedCornerShape(14.dp)) { Text("VER TREINO") } } } }

@Composable private fun DetailsScreen(state: GymUiState, start: () -> Unit, back: () -> Unit) { val workout = state.selectedWorkout ?: return; LazyColumn(Modifier.fillMaxSize().padding(20.dp), contentPadding = PaddingValues(top = 48.dp, bottom = 24.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { item { Text("‹  Voltar", color = MaterialTheme.colorScheme.primary, modifier = Modifier.clickable(onClick = back).padding(bottom = 16.dp)); Text(workout.name, style = MaterialTheme.typography.headlineLarge, fontWeight = FontWeight.Bold); Text(workout.description.orEmpty(), color = MaterialTheme.colorScheme.onSurfaceVariant); Button(start, Modifier.fillMaxWidth().padding(vertical = 18.dp).height(54.dp), shape = RoundedCornerShape(16.dp)) { Text("INICIAR TREINO") } }; items(workout.sessions.firstOrNull()?.exercises.orEmpty()) { ExerciseCard(it) } } }
@Composable private fun ExerciseCard(exercise: WorkoutExercise) { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp)) { Column(Modifier.padding(18.dp)) { Text(exercise.name, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold); Text("${exercise.sets} séries  •  ${exercise.repetitions} reps  •  ${exercise.suggestedLoad ?: "Livre"} kg", modifier = Modifier.padding(top = 8.dp)); Text("Descanso ${exercise.restSeconds}s", color = MaterialTheme.colorScheme.primary, style = MaterialTheme.typography.labelLarge, modifier = Modifier.padding(top = 6.dp)); exercise.note?.let { Text(it, color = MaterialTheme.colorScheme.onSurfaceVariant, modifier = Modifier.padding(top = 8.dp)) } } } }

@Composable private fun SessionScreen(state: GymUiState, vm: GymViewModel) { val exercise = state.selectedWorkout?.sessions?.firstOrNull()?.exercises?.getOrNull(state.exerciseIndex) ?: return; Column(Modifier.fillMaxSize().padding(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { Text(state.selectedWorkout.name, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 36.dp)); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text(formatTime(state.elapsedSeconds), fontSize = 28.sp, fontWeight = FontWeight.Bold); Text("${state.completedSets}/${state.totalSets} séries", color = MaterialTheme.colorScheme.primary) }; LinearProgressIndicator({ state.completedSets.toFloat() / state.totalSets.coerceAtLeast(1) }, Modifier.fillMaxWidth()); Spacer(Modifier.height(18.dp)); Text(exercise.name, style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold); Text("Série ${state.setNumber} de ${exercise.sets}", color = MaterialTheme.colorScheme.onSurfaceVariant); Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(24.dp), colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer)) { Column(Modifier.padding(24.dp)) { Text(exercise.repetitions, fontSize = 40.sp, fontWeight = FontWeight.Black); Text("repetições", color = MaterialTheme.colorScheme.onPrimaryContainer); Text("${exercise.suggestedLoad ?: "Livre"} kg", fontSize = 24.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 14.dp)) } }; if (state.restRemainingSeconds > 0) RestPanel(state, vm) else Button(vm::completeSet, Modifier.fillMaxWidth().height(58.dp), shape = RoundedCornerShape(16.dp)) { Text("CONCLUIR SÉRIE", fontWeight = FontWeight.Bold) }; TextButton(vm::finish, Modifier.align(Alignment.CenterHorizontally)) { Text("Finalizar treino") } } }
@Composable private fun RestPanel(state: GymUiState, vm: GymViewModel) { Card(Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.tertiaryContainer), shape = RoundedCornerShape(20.dp)) { Column(Modifier.padding(18.dp), horizontalAlignment = Alignment.CenterHorizontally) { Text("DESCANSO", style = MaterialTheme.typography.labelLarge); Text(formatTime(state.restRemainingSeconds), fontSize = 42.sp, fontWeight = FontWeight.Black); Row { OutlinedButton(vm::addRest) { Text("+30 segundos") }; Spacer(Modifier.width(10.dp)); TextButton(vm::skipRest) { Text("Pular") } } } } }
@Composable private fun SummaryScreen(state: GymUiState, home: () -> Unit) { Column(Modifier.fillMaxSize().padding(28.dp), verticalArrangement = Arrangement.Center, horizontalAlignment = Alignment.CenterHorizontally) { Text("Treino concluído", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold); Text("Bom trabalho, ${state.user?.name ?: "atleta"}!", modifier = Modifier.padding(top = 10.dp)); Text(formatTime(state.elapsedSeconds), fontSize = 48.sp, fontWeight = FontWeight.Black, color = MaterialTheme.colorScheme.primary, modifier = Modifier.padding(vertical = 24.dp)); Text("${state.completedSets} séries concluídas", color = MaterialTheme.colorScheme.onSurfaceVariant); Button(home, Modifier.fillMaxWidth().padding(top = 28.dp).height(54.dp)) { Text("VOLTAR PARA HOME") } } }
private fun formatTime(seconds: Long) = "%02d:%02d".format(seconds / 60, seconds % 60)
